### ISSUE TITLE
Build without CUDA

### ISSUE THREAD

**Issue by pclausen** [mohamed82008/TopOpt.jl#2]
Hi Mohamed

Pleasure to meet you at the WCSMO-13.
Is there a way to build without CUDA ? Thanks.

/Peter Clausen

**Comment by mohamed82008** [comment]
Not currently, this is one of the usability issues I need to work on which I talked about in my presentation. It should be somewhat straightforward to remove the GPU functionality into a submodule and load it conditionally based on a global environment variable.

**Comment by mohamed82008** [comment]
Could be a nice airport pastime activity!

**Comment by mohamed82008** [comment]
Done. Please follow the updated setup instructions:
```julia
using Pkg

pkg"add https://github.com/mohamed82008/JuAFEM.jl#master"
pkg"add https://github.com/mohamed82008/IterativeSolvers.jl#master"
pkg"add https://github.com/mohamed82008/VTKDataTypes.jl#master"
pkg"add https://github.com/mohamed82008/KissThreading.jl#master"
pkg"add https://github.com/mohamed82008/TopOpt.jl#master"
```
Happy coding!

**Comment by mohamed82008** [comment]
Closed via https://github.com/mohamed82008/TopOpt.jl/commit/b591fa9e87f35459d603d7b00ef4e164b1acaacb.
