### ISSUE TITLE
“Pkg.resolve()”.

### ISSUE THREAD

**Issue by OVGULIU** [mohamed82008/TopOpt.jl#7]
Hello,

I cannot solve this problem using “Pkg.resolve()”. I have installed CatViews.......

ERROR: LoadError: LoadError: ArgumentError: Package **TopOpt does not have CatViews in its dependencies**:
- If you have TopOpt checked out for development and have
  added CatViews as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with TopOpt

**Comment by mohamed82008** [comment]
Sorry for getting back to you late. I will look into it.

**Comment by OVGULIU** [comment]
@mohamed82008   Thank you in adavance!

**Comment by mohamed82008** [comment]
Could you remove TopOpt and reinstall it? I tried installing it afresh and it works fine.
```julia
(testproj) pkg> st
    Status `~\testproj\Project.toml`
  [42fd0dbc] IterativeSolvers v0.8.1+ #master (https://github.com/mohamed82008/IterativeSolvers.jl)
  [30d91d44] JuAFEM v0.2.0 #master (https://github.com/mohamed82008/JuAFEM.jl)
  [ece10b52] KissThreading v0.0.0 #master (https://github.com/mohamed82008/KissThreading.jl)
  [53a1e1a5] TopOpt v0.0.0 #master (https://github.com/mohamed82008/TopOpt.jl)
  [10d27dd1] VTKDataTypes v0.0.0 #master (https://github.com/mohamed82008/VTKDataTypes.jl)
```

**Comment by OVGULIU** [comment]
I have just reinstalled. it does not work... maybe I am using JuliaPro 1.2.0, thus we can not use in such IDE??

**Comment by mohamed82008** [comment]
Could you report the output of `] st`?

**Comment by OVGULIU** [comment]
(v1.2) pkg> st
    Status `C:\Users\david\.juliapro\JuliaPro_v1.2.0-1\environments\v1.2\Project.toml`
  [c52e3926] Atom v0.11.3
  [81a5f4ea] CatViews v1.0.0
  [fbcbbc08] FEMBase v0.3.1 #master (https://github.com/JuliaFEM/FEMBase.jl.git)
  [353fb843] FEMBasis v0.3.1 #master (https://github.com/JuliaFEM/FEMBasis.jl.git)
  [dcdf9ed5] FEMSparse v0.1.0
  [1a297f60] FillArrays v0.8.2
  [7073ff75] IJulia v1.20.2
  [42fd0dbc] IterativeSolvers v0.8.1+ #master (https://github.com/mohamed82008/IterativeSolvers.jl)
  [30d91d44] JuAFEM v0.2.0 #master (https://github.com/mohamed82008/JuAFEM.jl)
  [f80590ac] JuliaFEM v0.5.1
  [e5e0dc1b] Juno v0.7.2
  [ece10b52] KissThreading v0.0.0 #master (https://github.com/mohamed82008/KissThreading.jl)
  [ee78f7c6] Makie v0.9.5
  [48a634ad] Tensors v1.4.0
  [53a1e1a5] TopOpt v0.0.0 #master (https://github.com/mohamed82008/TopOpt.jl)
  [10d27dd1] VTKDataTypes v0.0.0 #master (https://github.com/mohamed82008/VTKDataTypes.jl)
  [b99e7846] BinaryProvider

**Comment by mohamed82008** [comment]
Please try removing and installing it again. I think I pushed a fix.

**Comment by OVGULIU** [comment]
just remove topopt??

**Comment by mohamed82008** [comment]
Yes, run:
```julia
using Pkg
pkg"rm TopOpt"
pkg"add https://github.com/mohamed82008/TopOpt.jl#master"
```

**Comment by OVGULIU** [comment]
Hey, it works! but still a warning

 ```
Warning: Package TopOpt does not have FillArrays in its dependencies:
│ - If you have TopOpt checked out for development and have
│   added FillArrays as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with TopOpt
└ Loading FillArrays into TopOpt from project dependency, future warnings for TopOpt are suppressed
```

**Comment by mohamed82008** [comment]
Fixed now. If you reinstall again, it should be fixed.

**Comment by mohamed82008** [comment]
May I ask what you want to use the program for? It is still under heavy development but mostly in another private repo.
